
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HanchaoLi/sell-bed-config.git
          username: HanchaoLi
          password: li8319426
          basedir: /Users/hanchao.li/Desktop/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

